// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYQA6FvvBiBXJOfUiRck_ObQvEw7Xw30',
    appId: '1:598348382140:web:f8effe933f1b0dc38835b9',
    messagingSenderId: '598348382140',
    projectId: 'bakaata-721d7',
    authDomain: 'bakaata-721d7.firebaseapp.com',
    storageBucket: 'bakaata-721d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBUejjgtVMI8vIvy7kl-MM7Ine1dOVKck',
    appId: '1:598348382140:android:8e47fc9aada2fc978835b9',
    messagingSenderId: '598348382140',
    projectId: 'bakaata-721d7',
    storageBucket: 'bakaata-721d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKe6jbBMvADnThK-57W32PZ2ceu8R-D8',
    appId: '1:598348382140:ios:49b4fc43adccadd58835b9',
    messagingSenderId: '598348382140',
    projectId: 'bakaata-721d7',
    storageBucket: 'bakaata-721d7.appspot.com',
    androidClientId: '598348382140-msi57a297s5bdos6elu2272f2nlhvdga.apps.googleusercontent.com',
    iosClientId: '598348382140-2k4hb81nopeunfm5oijl2da7av3d7vk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakaata',
  );
}
